name: Publish @foal/core to GitHub Packages

on:
  push:
    tags:
      - '*.UC'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@foal'
      
      - name: Install project and package dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      
      - name: Build @foal/core package with Lerna
        run: npx lerna run build --scope=@foal/core
      
      - name: Publish @foal/core to GitHub Packages
        run: npm publish
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
